{% set name = "eo-dataflow-report" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/eo-dataflow/eo-dataflow-report/-/archive/{{ version }}/eo-dataflow-report-{{ version }}.tar.gz
  sha256: 3608ece231b1e2498991ecd56a45a2880aa33e1c2bf25ac16966b50c34c8943f

build:
  number: 0
  script_env:
    - POETRY_DYNAMIC_VERSIONING_BYPASS={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - eo-dataflow-index-reports = eo_dataflow_report.cli.index_reports:index_reports
    - eo-dataflow-create-dashboards = eo_dataflow_report.cli.create_dashboards:create_dashboards


requirements:
  host:
    - python >=3.8
    - poetry-core
    - poetry-dynamic-versioning
    - pip

  run:
    - python >=3.8
    - elasticsearch >=7.17.0,<7.18
    - pydantic >=1.9.0,<2.0
    - numpy >=1.22.2,<1.23
    - pandas >=1.4.1,<1.5
    - pyarrow >=7.0.0,<8.0.0
    - shapely >=1.8.0,<1.9.0
    - xarray >=0.19
    - jinja2 >=3.0.3,<3.1.0
    - pyaml >=6.0

test:
  imports:
    - eo_dataflow_report

about:
  home: https://gitlab.ifremer.fr/eo-dataflow/eo-dataflow-report
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Checks online services for changed in data files, and downloads them when needed.

extra:
  recipe-maintainers:
    - marie59
